source "https://rubygems.org"

gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'sqlite3'
gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'rake'
gem 'rspec'
gem 'rack-test'
gem 'nokogiri'
gem 'capybara'
gem 'watir-webdriver'
gem 'rack'
gem 'sinatra'
gem 'sinatra-contrib'